from rules.snake_helper import *

configfile: "config/config.yaml"

include: "rules/sample_convert.smk"
include: "rules/sample_singlechannel.smk"
include: "rules/fishdot.smk"
include: "rules/segmentation.smk"
include: "rules/integration_summarize.smk"
include: "rules/integration_processing.smk"

localrules: all, integration

rule all:
    input:
        #"processed/per/Apr 2022 ZT0/single_channel/fish_t1"
        #output_sample_dirs(workflow="convert",config=config,target=None),
        output_sample_dirs(workflow="fishdot", config = config, target=None),
        output_sample_dirs(workflow="segmentation", config = config, target=None)

print(output_workflow_all(config))

rule integration:
    input:
        #join("results","probe_1","integration", output_workflow_all(config), "samples.csv"),
        join("results","probe_1","integration", output_workflow_all(config), "dots.csv")