from rules.snake_helper import *

configfile: "config/config.yaml"

include: "rules/sample_convert.smk"
include: "rules/sample_singlechannel.smk"
include: "rules/fishdot.smk"
include: "rules/segmentation.smk"
include: "rules/integration_summarize.smk"
include: "rules/integration_processing.smk"

localrules: all, int_sum, int_plot

rule all:
    input:
        #"processed/per/Apr 2022 ZT0/single_channel/fish_t1"
        #output_sample_dirs(workflow="convert",config=config,target=None),
        output_sample_dirs(workflow="fishdot", config = config, target=None),
        output_sample_dirs(workflow="segmentation", config = config, target=None)

print("parameter combination is " + output_workflow_all(config))

rule int_sum:
    # Step I integration - create summary and dot overlap files
    input:
        output_integration_all(stage = "summarize", config = config)

rule int_plot:
    # Step II integration - create the count plot
    # Requires modification to the integration output
    input:
        output_integration_all(stage = "plot", config = config)

rule int_qc:
    # Step II integration - create the QC plots
    # Requires modification to the integration output
    input:
        output_integration_all(stage="qc",config=config)