cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --mail-user=yeyu@umich.edu
    --mail-type=FAIL
    --account=swathi0
    --time={resources.time}
default-resources:
  - partition=standard
  - mem_mb=1000
  - time="1:00:00"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 600
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
cluster-cancel: /gpfs/accounts/swathi_root/swathi0/yeyu/rnaseq/smk/scancel_parsed
cluster-cancel-nargs: 50